# config/__init__.py
from .inputs import SURVEILLANCE, CONSTANTS, HR, EQUIPMENT, CONSUMABLES, OVERHEAD, ANNUALIZATION

__all__ = [
    "SURVEILLANCE", "CONSTANTS", "HR",
    "EQUIPMENT", "CONSUMABLES", "OVERHEAD", "ANNUALIZATION",
]
